### ISSUE TITLE
Request: Text Leader Control

### ISSUE THREAD

**Issue by Chrono9084** [johnpierson/RhythmForDynamo#12]
First off, thanks for the awesome Dynamo Package!  I am hoping that maybe you could implement a few nodes that are very similar to a few nodes you already have.

Currently you have Tags.GetLeaderElbow, Tags.GetLeaderEnd, Tags.SetLeaderEndPosition, and Tags. SetLeaderElbowPosition.

I am hoping that you would be able to make text note versions of these nodes so that the user can use the same functionality with text.

Is this possible?

Thanks in advance!

**Comment by johnpierson** [comment]
Yep! Let me see about getting these added to the next release.

**Comment by johnpierson** [comment]
@Chrono9084 This is in the source code now and will be on the package manager soon.

**Comment by johnpierson** [comment]
![image](https://user-images.githubusercontent.com/15744724/50978890-94852a00-14b2-11e9-89ac-1688bc4e850e.png)

**Comment by johnpierson** [comment]
Download version 2019.1.21 and let me know if the new node works for you.

**Comment by Chrono9084** [comment]
Sorry for the delayed response, I upgraded to 2019.1.21 and I am not seeing these nodes.

**Comment by johnpierson** [comment]
Well, looks like I might have jacked that up. Let me investigate

**Comment by johnpierson** [comment]
Yep! My fault. Try this version
![image](https://user-images.githubusercontent.com/15744724/54390481-31597480-4668-11e9-8155-c1770c0162a2.png)

**Comment by Chrono9084** [comment]
I will try it first thing in the morning and let you know how it works.  Thanks!

**Comment by Chrono9084** [comment]
John, with that update I see the Leaders.GetLeaderElbow, Leaders.GetLeaderEnd, Leaders.SetLeaderEndPosition, and Leaders.SetLeaderElbowPosition nodes but I don't see the TextNotes.GetLeaders node which they rely upon.  Any thoughts?

**Comment by johnpierson** [comment]
Oy vey. I bet I left those out now. Let me get some other changes made and push a new release. Apologies.

**Comment by Chrono9084** [comment]
LOL, don't apologize.  You are creating a free tool for us to use.  You owe me nothing!  I just cant wait to use it once it is implemented.

Side note: I submitted a suggestion to Parallax for new features for Monocle.  I was curious if you have seen any of those ideas yet (wanting to make sure they came through since I didn't receive any confirmation).

Thanks again.

**Comment by johnpierson** [comment]
Thanks for the understanding! :) Was your feature request this one?

> I am fixing some old graphs and using version doge is great for helping me find outdated nodes that are now included in newer packages or built directly into dynamo.  Replacing all of these nodes can be quite time consuming and I believe that Dynamo users will be needing to update graphs for as long as Dynamo is around given the speed at which dynamo and it's packages are updated.

If so, I have it added to the backlog now and it would definitely be an awesome feature! This same question comes up on the issues page and forums monthly if not weekly. The only issue I have right now is, it is going to take quite a bit of work, which is sometimes hard to justify for a free tool. 😟 I actually hope to make that a hackathon project one day to give it some momentum.

**Comment by Chrono9084** [comment]
Well...I would pay for the tool if it worked.  I have 100 users working with my Dynamo graphs and keeping them working is challenging sometimes.  :)

**Comment by johnpierson** [comment]
Definitely, appreciate the extra info! As I said, this is in the backlog and I will see where we can get with it.  Since there are a lot of [wishlist ](https://github.com/DynamoDS/Dynamo/issues?q=is%3Aissue+is%3Aopen+label%3Awishlist)type if things for Dynamo as well it could turn into a whole suite of tools I bet.
