### ISSUE TITLE
System.IO.FileLoadException

### ISSUE THREAD

**Issue by HVCFOG3Y34** [johnpierson/RhythmForDynamo#38]
**Describe the bug**
A Dynamo notification titled "System.IO.FileLoadException" and the description reads, "Dynamo has detected a conflict with a dependency and may be unstable. If any issues are detected, please uninstall addins or packages and contact the provider."

Contents when "Show Details" is expanded (2 pasted below. One isn't related to the package, but I figured I'd add it just in case):

`While loading assembly RhythmRevit, Version=2021.7.3.0, Culture=neutral, PublicKeyToken=null, Dynamo detected that the dependency AdWindows, Version=2018.11.1.0, Culture=neutral, PublicKeyToken=null was already loaded with an incompatible version. It is likely that another Revit Addin has loaded this assembly, please try uninstalling other Addins, and starting Dynamo again. Dynamo may be unstable in this state.
It is likely one of the following assemblies loaded the incompatible version:
UIFrameworkInterop, UIFramework, UIFrameworkServices, AdApplicationFrame, RevitAPIUI, Autodesk.LoadAutodeskFamily.Application, Autodesk.Revit.CloudRendering.Application, ConnectedDesktopUI`

`While loading assembly Autodesk.Forge, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null, Dynamo detected that the dependency RestSharp, Version=106.3.1.0, Culture=neutral, PublicKeyToken=598062e77f915f75 was already loaded with an incompatible version. It is likely that another Revit Addin has loaded this assembly, please try uninstalling other Addins, and starting Dynamo again. Dynamo may be unstable in this state.
It is likely one of the following assemblies loaded the incompatible version:
GregRevitAuth, Greg, DynamoPackages`

**Steps to Reproduce**
Load Rhythm package into Dynamo in Revit 2022.

**Expected behavior**
No errors when loaded.

**My setup**
- Operating System: Windows 10
- Dynamo version: 2.12.0
- Rhythm version: 2021.7.3
- Revit version: 22.1.1.516

**Comment by johnpierson** [comment]
AdWindows is shipped with Revit. The error is ignorable in this case
because I’m just loading an older version of that DLL. Dynamo is a bit over
zealous with these warnings and they are largely ignorable. Some history
https://forum.dynamobim.com/t/conflict-in-archi-lab-net/12298/28
