### ISSUE TITLE
Isolated Pick Model Elements

### ISSUE THREAD

**Issue by HVCFOG3Y34** [johnpierson/RhythmForDynamo#39]
**Describe the bug**
Isolated Pick Model Elements does not work. Pops up message to select elements and hit finished when done, but never lets you select any objects.

**Steps to Reproduce**
Place "Isolated Pick Model Elements" node, connect a "Categories" node (OOTB), Select category (in my case "Railings"), run graph. 

**Expected behavior**
Be able to select objects after prompt to 'Press finish to complete'.

**My setup**
- Operating System: Windows 10
- Dynamo version: 2.12.0
- Rhythm version: 2021.7.3
- Revit version: 22.1.1.516

**Comment by HVCFOG3Y34** [comment]
I should note that if you edit the node and switch the python node to use python 2, it works fine, but once it's set to python 3, it breaks.

**Comment by johnpierson** [comment]
Thanks for the report. If you aren't using Dynamo player, I suggest using the OOTB node for this
![image](https://user-images.githubusercontent.com/15744724/141194871-7df6e8a7-aded-4c4d-8458-97855760f33a.png)

**Comment by HVCFOG3Y34** [comment]
I am using the Dynamo player. For now, I just copied the python node out of your node into the main graph and switched it to python 2.

**Comment by johnpierson** [comment]
This is the replacement you should use in the future. But if copying the .py works for now, that's cool too. :) 
![image](https://user-images.githubusercontent.com/15744724/147686369-49db2f5e-87f7-4126-a45e-61777b0acd1e.png)
