### ISSUE TITLE
ReferencePlanes in Mass Family

### ISSUE THREAD

**Issue by timhevel** [johnpierson/RhythmForDynamo#40]
**What is the problem that needs solving?**
I'm trying to make referenceplanes in a mass family using ReferencePlanes.ByLine
but doc.Create only works for revit projects.

**How would you like to see it solved?**
Add an if-else or something to check if the active document is a project or a family and use doc.Create or doc.FamilyCreate respectively.

**Describe alternatives you've considered**
none

**Additional context**
(Please fill in if applicable. Add any other context or screenshots about the feature request here.)

**Comment by johnpierson** [comment]
Great suggestion! This was an easy add so I knocked it out really quick.

In action here:
![20220107-createRefPlane](https://user-images.githubusercontent.com/15744724/148572335-334b1179-cebf-4356-ab21-226784125da5.gif)
 
and it is in the latest release on the package manager:
v 2022.1.1

**Comment by timhevel** [comment]
♡
