### ISSUE TITLE
FamilyInstances.RetrieveNestedComponent node is not working with linked Revit files

### ISSUE THREAD

**Issue by ElieTRAD** [johnpierson/RhythmForDynamo#42]
**Describe the bug**
any chance to fix the ʳʰʸᵗʰᵐ|FamilyInstances.RetrieveNestedComponents so it can get nested families out of families found in links?

**Steps to Reproduce**
linkElement as output is not working.

![FamilyInstances RetrieveNestedComponents](https://user-images.githubusercontent.com/55875794/170644117-fc90ab24-7e61-4124-8437-7f7186778136.jpeg)
#[RhythmForDynamo/FamilyInstance.cs at 8381eb1a24d49f0e53282ab47938c469e4340af7 · johnpierson/RhythmForDynamo · GitHub](https://github.com/johnpierson/RhythmForDynamo/blob/8381eb1a24d49f0e53282ab47938c469e4340af7/src/Rhythm/Revit/Elements/FamilyInstance.cs#L154-L194)

**Comment by johnpierson** [comment]
May I ask what that python script is?

**Comment by johnpierson** [comment]
Cool cool. Next question, what is your downstream use-case for this?
