### ISSUE TITLE
Document.CopyElementsFromDocument

### ISSUE THREAD

**Issue by rizzoblo** [johnpierson/RhythmForDynamo#43]
The idea to use this node was copying in sections and elevations into a project that didnt have the types already created. 
![Error](https://user-images.githubusercontent.com/49462811/174674008-c487f682-03b5-4663-bbad-a8065c128470.png)
Running this crashed dynamo once and after restarting and trying again I got an ambiguous error on the copyelementsfromdocument node.  Perhaps Im not using this as intended.  If you have a better idea to transfer the families and setup for callouts, elevations, and sections, I am all ears.

**Comment by johnpierson** [comment]
hmm, are you able to share sample RVTs for me to debug with?

**Comment by johnpierson** [comment]
So this node was actually meant as more of a "family loader" for wall types and various family types. Revit gets really weird with live views and view-specific elements and it requires quite a bit of rework to do it "right".

As of right now, this node does not support this, but I will update it to reflect my comments above.

**Comment by johnpierson** [comment]
However, to do what I think you are trying to do, this should do it:
![image](https://user-images.githubusercontent.com/15744724/175064577-63d39bf7-d4e3-4654-bc39-89721b150854.png)

**Comment by rizzoblo** [comment]
That mostly works.  When I followed this in 2022 it worked.  2023 didnt
have the same nodes and I was getting errors.

If I manually use transfer project standards, I get the option to override
duplicate types

[image: image.png]

When I use the method you suggested, I get a dialog that the project types
will be used.

[image: image.png]

How would you go about overwriting the project.

Im trying to build a project updater that does a bunch of steps instead of
a few manual steps and am getting hung up at this part still.  Not really
your problem, but wondering if maybe there could be a bool option to
overwrite in your node like the first dialog functions or perhaps another
combination that will force overwrite?

Thanks for the help already John.

Rob
