### ISSUE TITLE
Missing nodes in package for Revit 2020

### ISSUE THREAD

**Issue by Lazarica-t** [johnpierson/RhythmForDynamo#50]
**Describe the bug**
Hi, there seams to be some nodes missing in the latest version 2022.10.2 when working with Revit 2020. I don't know if this is normal, but in version 2022.9.1 they are present.

![image](https://user-images.githubusercontent.com/49474519/200318408-70f12741-4802-4310-80c1-d742ac2e54fa.png)

![image](https://user-images.githubusercontent.com/49474519/200319453-088dae61-288e-45fc-8741-80e76afed520.png)

**My setup**
- Operating System: Windows 11
- Dynamo version: 2.3
- Rhythm version: 2022.10.2
- Revit version: 2020.2.8

**Comment by johnpierson** [comment]
Hmm. 2022.9.1 might be the last one to support Revit 2020 then. I’ll double
check.

**Comment by veryshinything** [comment]
Hi John,

I'm not sure if this is happening to others along this same line.  Tested 2.16 / 2023 and 2.13 / 2022 installed from package manager and downloaded separately from dynamopackages.com a variety of versions.  dyf folder is coming in either blank or only contains 11 nodes, same as the 2022.10.2 image.

**Comment by johnpierson** [comment]
DYFs have been removed. And for support for versions 2020 and older, you have to install this specific version.

https://forum.dynamobim.com/t/helpers-user-message-node-from-rhythm-package/85870/11
