### ISSUE TITLE
CurtainGridLine.SkippedSegmentCurves fails to return multiple segments

### ISSUE THREAD

**Issue by chartreuseUNICORN** [johnpierson/RhythmForDynamo#52]
**Describe the bug**
If a CurtainGridLine has SkippedSegmentCurves that are not continuous, this node returns no value.  The conversion to prototype attempts to generate a polycurve, but dynamo doesn't support discontinuous polycurves.

**Steps to Reproduce**
create a curtain grid and remove two noncontinuous segments, pass that CurtainGridLine into the node

**Expected behavior**
The DB class is a CurveArray, so i would expect it to return a list of curves instead of trying to generate a polycurve

**My setup**
- Operating System: Windows 10
- Dynamo version: 2.12.1.8246
- Rhythm version: 2022.11.3
- Revit version: 22.1.30.34

**Comment by johnpierson** [comment]
interesting! The Core Dynamo `ToProtoType` call tries to do that poly curve conversion for us. Kind of annoying, but I can fix.

**Comment by johnpierson** [comment]
Download the latest update to get access.
