### ISSUE TITLE
revit 2019 back support

### ISSUE THREAD

**Issue by tjxme** [johnpierson/RhythmForDynamo#53]
**Describe the bug**
(Please fill in. A clear and concise description of what the bug is. In most cases, it will be helpful if you include journal files.)
hi Im still using Revit 2019, however, the area.boundaries does not work for me.
keeps says. i tried with python script, as long as i put ToProtoType(). it will give me the error. does anything change in 2020?
The type initializer for ‘Autodesk.LibG.LibGPINVOKE’ threw an exception

**Steps to Reproduce**
(Please fill in. What did you do, step by step?)

**Expected behavior**
(Please fill in. A clear and concise description of what you expected to happen.)

**My setup**
- Operating System: ................win10
- Dynamo version: ................2.0.6
- Rhythm version: ................2023.2
- Revit version: ................2019

**Comment by johnpierson** [comment]
Hmm, 2019 is going to be a bit difficult to support for me as I don't even have it installed. 

But, have you tried installing the version referenced here: https://forum.dynamobim.com/t/helpers-user-message-node-from-rhythm-package/85870/11

The next thing to do would be to install a way older version perhaps.

**Comment by johnpierson** [comment]
Unfortunately, I will not be able to add support for Revit 2019. At this time Rhythm supports the most recent 4 versions of software.  This is to mirror Autodesk's own support standards https://www.autodesk.com/support/account/manage/versions/support-lifecycle
