### ISSUE TITLE
Viewport.Create not working in 2024

### ISSUE THREAD

**Issue by AndrewVessey** [johnpierson/RhythmForDynamo#54]
Hi,
The Viewport.Create node is not working in 2024.  Do you know why or if it will be a easy fix?

Thank you.

Receive:
Warning
Viewport.Create operation failed
Method not found: 'Int32
Revit.Elements.Eleemnt.get_Id()'.

**My setup**
- Operating System: Windows 10
- Dynamo version: v.2.17.0
- Rhythm version: 2023.4.2024
- Revit version: 2024

[journal.0018.txt](https://github.com/johnpierson/RhythmForDynamo/files/11297878/journal.0018.txt)
[journal.0018.worker1.log](https://github.com/johnpierson/RhythmForDynamo/files/11297879/journal.0018.worker1.log)

**Comment by johnpierson** [comment]
Ah yes. This is a Revit 2024 change and I need to account for it.

**Comment by J3deye** [comment]
@johnpierson I am having the same issue. Are there any alternatives? Thanks!

**Comment by johnpierson** [comment]
Nothing yet. I am trying to find time to update it

**Comment by johnpierson** [comment]
This should be fixed in Rhythm v.2023.7.3
