### ISSUE TITLE
Applications.OpenDocumentFile ability to handle error messages

### ISSUE THREAD

**Issue by GvBeers** [johnpierson/RhythmForDynamo#65]
**What is the problem that needs solving?**
Applications.OpenDocumentFile ability to handle error messages

**How would you like to see it solved?**
Possibility to give a choice of how to deal with error messages instead of having to answering them via the Revit UI.

**Describe alternatives you've considered**
None yet, script now seems to be waiting for input if needed. And I wouldn't know how to overcome this. Which is not good for the lead time.

**Comment by johnpierson** [comment]
Do you have an example of the specific error message you are trying to suppress? Generally, it is not advisable to simply dismiss all warnings. It is often better to just fix them.

**Comment by johnpierson** [comment]
@GvBeers if you can try out the latest version of Rhythm and let me know if it helps.
