### ISSUE TITLE
Need confirm process to update

### ISSUE THREAD

**Issue by chuongmep** [johnpierson/RhythmForDynamo#66]
Hi @johnpierson, is your are resolving conflict between branch master and branch dev?

**Comment by johnpierson** [comment]
We are going to have to recreate the dev branch. The changes you made were a bit premature, unfortunately, resulting in far too many conflicts between my other branch that I was working on.

I understand if you do not want to redo the work, but that is where we are/

**Comment by johnpierson** [comment]
If you are willing to still contribute, please base all changes off of this new dev branch: 

https://github.com/johnpierson/RhythmForDynamo/tree/dev

**Comment by chuongmep** [comment]
Thank you for you informaton, I will consider remodify when I have time to colaborate , need re work all now.

**Comment by johnpierson** [comment]
Thanks again! Sorry about that, but there was far too much work on my end that was going lost.

**Comment by johnpierson** [comment]
Hey @chuongmep future pull requests need to be from scratch. Not merely pointing at the new master with the 137 changed files. Please start a fresh branch if you want to do this still. Your PR as is, is breaking way too much stuff on my end.
