### ISSUE TITLE
Revit 2022 Scope Boxes Node Glitch

### ISSUE THREAD

**Issue by joseph-kirkpatrick** [johnpierson/RhythmForDynamo#69]
**Describe the bug**
When reopening this script, not even running it, I noticed that the Scope Boxes node had 2 outputs listed for the same item
![image](https://github.com/johnpierson/RhythmForDynamo/assets/32959656/26ef5885-e95b-4f8c-aa91-44287a1d06ea)

**Steps to Reproduce**
I deleted the shown node, readded the node, save closed, then reopened everything without running the script and it showed the same. Now every time I open the script the Scope Boxes node has another output for Scope Box, it will continue doing it every time I open the Script.

**Expected behavior**
Expected behavior is that node doesn't add additional outputs to itself when opening the script

**My setup**
- Operating System: Windows 11
- Dynamo Core version: 2.12.1.8246
- Dynamo Revit version: 2.12.1.11123
- Rhythm version: 2023.6.2022
- Revit version: 22.1.50.17

This is not the case in Revit 2023, this version works fine and doesn't duplicate the output.
- Dynamo Core version: 2.16.2.5624
- Dynamo Revit version: 2.16.2.9354
- Rhythm version: 2023.6.2023
- Revit version: 23.1.30.97

**Comment by joseph-kirkpatrick** [comment]
After running without modifying the node it resulted Null and didn't work.
![image](https://github.com/johnpierson/RhythmForDynamo/assets/32959656/20651246-d41d-4035-bbd7-6149fd0b6322)

If I swap to a new node with 1 output, set as input save and close it doesn't work. And when I reopen it, it shows as the image above with 2 outputs.

If I move the output to the top out, it did work but shows the result as null while in full dynamo.
![image](https://github.com/johnpierson/RhythmForDynamo/assets/32959656/9cc74263-7f9b-48c3-9fc9-82c1cdce7444)

However when running it from the player it didn't work (it does still show the scope boxes as a drop down) but doesnt output the correct scope box. After opening the script again it now shows 3 outputs and has moved the previous output down and made 1 new output.
![image](https://github.com/johnpierson/RhythmForDynamo/assets/32959656/578f65f4-3f98-4f65-8fb4-4c361b006495)

**Comment by johnpierson** [comment]
Please update to the latest version of Rhythm. Unfortunately, these nodes ave now been removed because of these kind of things.
