### ISSUE TITLE
View.Viewport Node Issue

### ISSUE THREAD

**Issue by joseph-kirkpatrick** [johnpierson/RhythmForDynamo#70]
**Describe the bug**
(Please fill in. A clear and concise description of what the bug is. In most cases, it will be helpful if you include journal files.)
When adding list to Node it produces a null error in R23 but not R24. Both have the latest Rhythm package. R23 had the new package added and restarted to make sure all dll's have been loaded.

"Warning:
View.Viewport operation failed. Method not found: 'Int64 Revit.Elements.Element.get_Id()'. 
View.Viewport operation failed. Method not found: 'Int64 Revit.Elements.Element.get_id()'.

**Steps to Reproduce**
Feeding the View.Viewport node a list of views returns null, 

**Expected behavior**
Typically it just returns the viewport to feed into the rest of the graph

**My setup**
- Operating System: Windows 10
- Dynamo version: 2.16.2
- Rhythm version: 2024.3.1
- Revit version: 2023.1

![Dynamo R23 Rhythm](https://github.com/johnpierson/RhythmForDynamo/assets/32959656/8e03b967-7c6d-4297-9647-9032dee59172)

**Comment by johnpierson** [comment]
fixing now!

**Comment by joseph-kirkpatrick** [comment]
I was looking into a post from the link below and that does work but, it only results in 1 view port when feeding it the multiple lists. I really need to brush up on my python haha. Thanks for looking into this!!
 https://forum.dynamobim.com/t/get-view-from-viewport-python/74707/2

**Comment by johnpierson** [comment]
Yeah, this one is a Dynamo side issue for getting elements by id. (ToDSType())

**Comment by johnpierson** [comment]
New update will be live in the package manager in about 15 minutes.

**Comment by joseph-kirkpatrick** [comment]
I'll test it out in R24 and make sure everything is still good in that as well.

**Comment by joseph-kirkpatrick** [comment]
Confirmed, R23 and R24 both work! :)

**Comment by johnpierson** [comment]
Great to hear!!
